### PR TITLE
bump tmpnb

### PR DESCRIPTION
**Pull request by odewahn**
there was a tiny change required to update tmpnb.  It's still not 100% right, but it's good enough to get the point across tomorrow.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Might as well bump to tmp39 until the thebe PR https://github.com/oreillymedia/thebe/pull/50 is merged or a similar solution comes out.

**Comment by odewahn** [comment]
I tried tmp39, but the interact bar doesn't work.  So, I kept going backward until it did.  We should probably talk with Zach about it tomorrow, but I doubt he can fix it tonight.

**Comment by rgbkrk** [comment]
What's up with the interact bar? /cc @parente

I wonder if it's differences in ipywidgets...

**Comment by parente** [comment]
`ipywidgets                4.0.3                    py34_0`

is the version of ipywidgets installed in the latest build. Just ran https://github.com/ipython/ipywidgets/blob/master/examples/Using%20Interact.ipynb on tmp39 and it seems fine FWIW.

**Comment by rgbkrk** [comment]
Yeah, I think this is related to thebe bundling a specific version of e.g. the widgets. We'd need versioning of thebe tied to versions of the notebook (until we finish the broken apart JS libraries).

**Pull request merged**
